---
title: "Second R Markdown Assignment"
author: "Winnie Chen"
date: "September 16, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment="")
```

In a previous video I showed you how to read in data and update to GitHub.  I want you take the data on Poinsettias provided.  I want you to explore the data, creating tables and graphics and write up a descriptive report about your observations.  Your report should include the following:  

- a table summarizing the data with a caption
table= table(Poinsettias$color)




barplot(table, xlab = "Colors", main = "Poinsettias Colors", col = c("pink", "red", "white"))


**Note:** I did not show you how to do everything in this assignment in a video, but the R Markdown lesson page and a quick google search will help you do the above.  

The final assignment and data set should be uploaded into a repository on your GitHub account.  You will submit a link to the repository name as your final assigment.  


